# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Eking"
product_name = "mypad"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Eking"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_22", "P0_20", "P0_17", "P0_15", "P0_02"]
output_pins = ["P0_09", "P0_10", "P1_06", "P1_04"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 5
cols = 4
layers = 2
# ┌───┬───┬───┬───┐
# │NUM│ / │ * │ - │ 
# ├───┼───┼───┼───┤
# │ 7 │ 8 │ 9 │   │
# ├───┼───┼───┤ + │
# │ 4 │ 5 │ 6 │   │
# ├───┼───┼───┼───┤
# │ 1 │ 2 │ 3 │ E │
# ├───┴───┼───┤ N │
# │   0   │ . │ T │
# └───────┴───┴───┘
matrix_map = """
(0,0) (0,1) (0,2) (0,3)
(1,0) (1,1) (1,2) (1,3)
(2,0) (2,1) (2,2)
(3,0) (3,1) (3,2) (3,3)
(4,0)       (4,2) 
"""
# layer 0 (default):
[[layer]]
name = "1" #optional name for the layer
keys = """
NumLock KpSlash KpAsterisk KpMinus
Kp7     Kp8     Kp9        KpPlus
Kp4     Kp5     Kp6
Kp1     Kp2     Kp3        Enter
Kp0             MO(2)
"""

# layer 1:
[[layer]]
name = "2" #optional name for the layer
keys = """
NumLock KpSlash KpAsterisk KpMinus
Kp7     Kp8     Kp9        KpPlus
Kp4     Kp5     Kp6
Kp1     Kp2     Kp3        Enter
Kp0             KpDot
"""


[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
