# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "mypad"
product_name = "mypad"
vendor_id = 0x616C
product_id = 0x0001
manufacturer = "Eking"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_22", "P0_20", "P0_17", "P0_15", "P0_02"]
output_pins = ["P0_09", "P0_10", "P1_06", "P1_04"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 5
cols = 4
layers = 3
# ┌───┬───┬───┬───┐
# │NUM│ / │ * │ - │
# ├───┼───┼───┼───┤
# │ 7 │ 8 │ 9 │   │
# ├───┼───┼───┤ + │
# │ 4 │ 5 │ 6 │   │
# ├───┼───┼───┼───┤
# │ 1 │ 2 │ 3 │ E │
# ├───┴───┼───┤ N │
# │   0   │ . │ T │
# └───────┴───┴───┘
matrix_map = """
(0,0) (0,1) (0,2) (0,3)
(1,0) (1,1) (1,2) (1,3)
(2,0) (2,1) (2,2)
(3,0) (3,1) (3,2) (3,3)
(4,0)       (4,2) 
"""

# layer 0 (default):
[[layer]]
name = "base_layer" #optional name for the layer
keys = """
NumLock KpSlash KpAsterisk KpMinus
Kp7     Kp8     Kp9        KpPlus
Kp4     Kp5     Kp6
Kp1     Kp2     Kp3        Enter
Kp0             TO(mouse_navigation)
"""

# layer 1: 
[[layer]]
name = "mouse_navigation" #optional name for the layer
keys = """
NumLock KpSlash KpAsterisk KpMinus
Kp7     Kp8     Kp9        KpPlus
Kp4     Kp5     Kp6
Kp1     Kp2     Kp3        Enter
Kp0             TO(base_layer)
"""

[ble]
# Whether to enable BLE feature
enabled = true
# nRF52840's saadc pin for reading battery level, you can use a pin number or "vddh"
battery_adc_pin = "vddh"
# The voltage divider setting for saadc. 
# For example, nice!nano have 806 + 2M resistors, the saadc measures voltage on 2M resistor, so the two values should be set to 2000 and 2806
adc_divider_measured = 2000
adc_divider_total = 2806
# Pin that reads battery's charging state, `low-active` means the battery is charging when `charge_state.pin` is low
#charge_state = { pin = "PIN_1", low_active = true }
# Output LED pin that blinks when the battery is low
#charge_led= { pin = "PIN_2", low_active = true }


[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
